train_config:
  env_name: "ant"
  train_type: "SGD-ppo"
  ticket_dir: "experiments/blines/ant_sepcma/b_1_eval_2/extra"
  model_config:
    hidden_layers: 2
    hidden_dims: 32
  task_config:
    max_steps: 500
  num_imp_iters: 20
  network_to_prune: "final"

log_config:
  time_to_track: ["imp_iter", "num_steps"]
  what_to_track: 
    - "final_perf"
    - "best_perf"
    - "test_perf"
  what_to_print:
    - "final_perf"
    - "best_perf"
    - "test_perf"
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"
  use_wandb: true
  wandb_config:
    project: es-lottery
    group: ppo-tickets-walker-48u
    name: seed0

device_config:
  device_type: "gpu"
  num_devices: 1