train_config:
  env_name: fmnist
  train_type: "SGD-mnist"
  ticket_dir: "experiments/fmnist_snes_128/b_1_eval_2/extra"
  # 176588, 362028, 381632, 562958, 924197
  model_config:
    hidden_layers: 0
    hidden_dims: 0
  lrate: 3e-04
  batch_size: 128
  num_epochs: 20
  task_config:
    batch_size: 1024
  num_imp_iters: 20
  fixed_seed: false

log_config:
  time_to_track: ["imp_iter", "num_gens"]
  what_to_track: 
    - "final_perf"
    - "best_perf"
    - "test_perf"
    - "train_perf"
  what_to_print:
    - "final_perf"
    - "best_perf"
    - "test_perf"
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"
  use_wandb: true
  wandb_config:
    project: es-lottery
    group: mnist-sgd
    name: seed0

device_config:
  device_type: "gpu"
  num_devices: 1