train_config:
  env_name: "CartPole-v1"
  num_generations: 2000
  eval_every_gen: 50
  strategy_name: "Sep_CMA_ES" #"Sep_CMA_ES" #"OpenES"
  popsize: 100
  normalize_obs: False
  es_config:
    mean_decay: 1e-04
  model_config:
    hidden_layers: 2
    hidden_dims: 64
  task_config:
    max_steps: 500
  es_params:
    init_min: 0.0
    init_max: 0.0
  eval_config:
    n_repeats: 8
    test_n_repeats: 1
    n_evaluations: 32
  num_imp_iters: 20
  imp_config:
    baseline_name: "sig2noise"
    prune_ratio: 0.8
    modules_not_to_prune: []
  network_to_prune: "final"
  fixed_seed: false

log_config:
  time_to_track: ["imp_iter", "num_gens"]
  what_to_track: 
    - "final_perf"
    - "best_perf"
    - "test_perf"
    - "train_perf"
    - "sparsity"
    - "trainable_params"
    - "pruned_params"
    - "prunable_params"
    - "prune_threshold"
  what_to_print:
    - "final_perf"
    - "best_perf"
    - "test_perf"
    - "sparsity"
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"
  use_wandb: true
  wandb_config:
    project: es-lottery
    group: diff-es-pendulum
    name: seed0

device_config:
  device_type: "gpu"
  num_devices: 1