train_config:
  env_name: "mnist"
  num_generations: 4000
  eval_every_gen: 100
  strategy_name: "Sep_CMA_ES"
  popsize: 128
  normalize_obs: False
  es_config:
    mean_decay: 1e-04
  model_config:
    hidden_layers: 0
    hidden_dims: 0
  task_config:
    batch_size: 1024
  es_params:
    init_min: 0.0
    init_max: 0.0
  eval_config:
    n_repeats: 1
    test_n_repeats: 1
    n_evaluations: 1
  num_imp_iters: 20
  imp_config:
    baseline_name: "sig2noise"
    prune_ratio: 0.8
    modules_not_to_prune: []
  network_to_prune: "final"
  fixed_seed: false

log_config:
  time_to_track: ["imp_iter", "num_gens"]
  what_to_track: 
    - "final_perf"
    - "best_perf"
    - "test_perf"
    - "train_perf"
    - "sparsity"
    - "trainable_params"
    - "pruned_params"
    - "prunable_params"
    - "prune_threshold"
  what_to_print:
    - "final_perf"
    - "best_perf"
    - "test_perf"
    - "sparsity"
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"
  use_wandb: true
  wandb_config:
    project: es-lth-crv
    group: pgpe-kmnist
    name: seed0

device_config:
  device_type: "gpu"
  num_devices: 1